"""This file contains a few short calculations whose output is spot checked
for accurracy. Additional, more thorough checks will make sure that the 
density matrices produced are legal.
"""
from math import ceil
import os
import json as json
import numpy as np
from tqdm import tqdm
from tenso.prototypes.bath import gen_bcf
from math import ceil
from tenso.prototypes.heom import system_multibath
from tenso.prototypes.heom import system_single_bath 
from tenso.prototypes.default_parameters import quantity
import pytest

def test1(subtests,tmp_path):
    """This tests a spin-boson calculation with a Drude-Lorentz and a
    Brownian term in the bath with the Pade decomposition. 
    """
    bath_simulation = gen_bcf(
        re_d=[540], # Reorganization energy (cm^{-1})
        width_d=[70], # Width of Drude-Lorentz spectral density (cm^{-1})
        freq_b=[1243], # Brownian spectral density frequency (cm^{-1})
        re_b=[161.6], # Brownian spectral reorganization energy (cm^{-1})
        width_b=[10], # Brownian spectral width (cm^{-1})
        temperature=300, # Temperature of the bath
        decomposition_method='Pade',
        n_ltc=1,) # Low temperature correction terms
    end_time = 10 # Propagation time in fs
    dt = 1 # Time step size in fs
    wfn = np.array([0.0, 1.0], dtype=np.complex128) # Initial wavefunction
    out=os.path.join(tmp_path,'hr1')

    # Generate the propagator that will advance the system
    propagator = system_multibath(
       fname=out, # Specify output file
       init_rdo=np.outer(wfn, wfn.conj()), # Set system initial condition
       sys_ham=np.array([[-750.0,300.0],[300.0,750.0]], dtype=np.complex128), # Set the system Hamiltonian (cm^{-1})
       sys_ops=[np.array([[-0.5,0.0], [0.0,0.5]], dtype=np.complex128)], # Set the H_{SB} system-bath coupling operator(s) (cm^{-1})
       bath_correlations=[bath_simulation], # Specify bath correlation function(s) generated by gen_bcf
       dim=25, # Hierarchy depth
       end_time=end_time, # End time of the simulation
       step_time=dt,) # Time step size
    # Perform the dynamics simulation and generate a progress bar
    progress_bar = tqdm(propagator,total=ceil(end_time/dt))
    for _t in progress_bar:
       progress_bar.set_description(f'@{_t: .2f} fs')

    # Load results from the output file into a local array
    results = np.loadtxt(out+".dat.log",dtype=np.complex128)
    assert results[9,1].real == pytest.approx(0.13728234)
    assert results[9,1].imag == pytest.approx(0.0)
    assert results[8,2].real == pytest.approx(0.23937323)
    assert results[8,2].imag == pytest.approx(-0.14636433)
    for i in range(0,10):
        with subtests.test("Values add to 1", i =i):
            assert results[i,1].real + results[i,4] == pytest.approx(1.0)
    for i in range(0,10):
        with subtests.test("No imaginary Populations", i=i):
            assert results[i,1].imag <= 1e-5
            assert results[i,4].imag <= 1e-5
    for i in range(0,10):
        with subtests.test("No negative Populations", i=i):
            assert np.absolute(results[i,1].real) >= -1e-5
            assert np.absolute(results[i,4].real) >= -1e-5
    for i in range(0,10):
        with subtests.test("Hermitian matrix", i=i):
            assert results[i,2].imag == pytest.approx(-1.0*results[i,3].imag)
            assert results[i,2].real == pytest.approx(results[i,3].real)
    for i in range(0,10):
        with subtests.test("No illegally large coherences", i=i): # Tolerance of 1% allowed
            assert np.sqrt(np.absolute(results[i,1]))*np.sqrt(np.absolute(results[i,4])) >= 0.99*np.abs(results[i,2])
            assert np.sqrt(np.absolute(results[i,1]))*np.sqrt(np.absolute(results[i,4])) >= 0.99*np.abs(results[i,3])


def test2(subtests,tmp_path):
    """This function tests a spin-boson problem with a Drude-Lorentz bath with
    the Pade decomposition."""
    bath_simulation = gen_bcf(
        re_d=[540,300], # Reorganization energy (cm^{-1})
        width_d=[70,35], # Width of Drude-Lorentz spectral density (cm^{-1})
        temperature=150, # Temperature of the bath
        decomposition_method='Pade',
        n_ltc=3,) # Low temperature correction terms
    end_time = 10 # Propagation time in fs
    dt = 1 # Time step size in fs
    wfn = np.array([0.0, 1.0], dtype=np.complex128) # Initial wavefunction
    out=os.path.join(tmp_path,'hr1')

    # Generate the propagator that will advance the system
    propagator = system_multibath(
       fname=out, # Specify output file
       init_rdo=np.outer(wfn, wfn.conj()), # Set system initial condition
       sys_ham=np.array([[-750.0,300.0],[300.0,750.0]], dtype=np.complex128), # Set the system Hamiltonian (cm^{-1})
       sys_ops=[np.array([[-0.5,0.0], [0.0,0.5]], dtype=np.complex128)], # Set the H_{SB} system-bath coupling operator(s) (cm^{-1})
       bath_correlations=[bath_simulation], # Specify bath correlation function(s) generated by gen_bcf
       dim=25, # Hierarchy depth
       end_time=end_time, # End time of the simulation
       step_time=dt,) # Time step size
    # Perform the dynamics simulation and generate a progress bar
    progress_bar = tqdm(propagator,total=ceil(end_time/dt))
    for _t in progress_bar:
       progress_bar.set_description(f'@{_t: .2f} fs')

    # Load results from the output file into a local array
    results = np.loadtxt(out+".dat.log",dtype=np.complex128)
    assert results[2,3].real == pytest.approx(0.03056787)
    assert results[9,4].real == pytest.approx(0.86644884)
    assert results[9,4].imag == pytest.approx(0.0)
    assert results[7,2].real == pytest.approx(0.23953274)
    assert results[7,2].imag == pytest.approx(-0.15912000)
    for i in range(0,10):
        with subtests.test("Values add to 1", i =i):
            assert results[i,1].real + results[i,4] == pytest.approx(1.0)
    for i in range(0,10):
        with subtests.test("No imaginary Populations", i=i):
            assert results[i,1].imag <= 1e-5
            assert results[i,4].imag <= 1e-5
    for i in range(0,10):
        with subtests.test("No negative Populations", i=i):
            assert np.absolute(results[i,1].real) >= -1e-5
            assert np.absolute(results[i,4].real) >= -1e-5
    for i in range(0,10):
        with subtests.test("Hermitian matrix", i=i):
            assert results[i,2].imag == pytest.approx(-1.0*results[i,3].imag)
            assert results[i,2].real == pytest.approx(results[i,3].real)
    for i in range(0,10):
        with subtests.test("No illegally large coherences", i=i): # Tolerance of 1% allowed
            assert np.sqrt(np.absolute(results[i,1]))*np.sqrt(np.absolute(results[i,4])) >= 0.99*np.abs(results[i,2])
            assert np.sqrt(np.absolute(results[i,1]))*np.sqrt(np.absolute(results[i,4])) >= 0.99*np.abs(results[i,3])


def test3(subtests,tmp_path):
    """This function tests a spin-boson problem with a Drude-Lorentz bath
    and the Matsubara decomposition.
    """
    bath_simulation = gen_bcf(
        re_d=[540], # Reorganization energy (cm^{-1})
        width_d=[70], # Width of Drude-Lorentz spectral density (cm^{-1})
        temperature=400, # Temperature of the bath
        decomposition_method='Matsubara',
        n_ltc=1,) # Low temperature correction terms
    end_time = 100 # Propagation time in fs
    dt = 1 # Time step size in fs
    wfn = np.array([0.0, 1.0], dtype=np.complex128) # Initial wavefunction
    out=os.path.join(tmp_path,'hr1')

    # Generate the propagator that will advance the system
    propagator = system_multibath(
       fname=out, # Specify output file
       init_rdo=np.outer(wfn, wfn.conj()), # Set system initial condition
       sys_ham=np.array([[-750.0,300.0],[300.0,750.0]], dtype=np.complex128), # Set the system Hamiltonian (cm^{-1})
       sys_ops=[np.array([[-0.5,0.0], [0.0,0.5]], dtype=np.complex128)], # Set the H_{SB} system-bath coupling operator(s) (cm^{-1})
       bath_correlations=[bath_simulation], # Specify bath correlation function(s) generated by gen_bcf
       dim=15, # Hierarchy depth
       end_time=end_time, # End time of the simulation
       frame_method='train',
       step_time=dt,) # Time step size
    # Perform the dynamics simulation and generate a progress bar
    progress_bar = tqdm(propagator,total=ceil(end_time/dt))
    for _t in progress_bar:
       progress_bar.set_description(f'@{_t: .2f} fs')

    # Load results from the output file into a local array
    results = np.loadtxt(out+".dat.log",dtype=np.complex128)
    assert results[25,3].real == pytest.approx(0.16789454)
    assert results[25,3].imag == pytest.approx(0.01214597)
    assert results[54,1].real == pytest.approx(0.16212476)
    assert results[54,1].imag == pytest.approx(0.0)
    assert results[81,4].real == pytest.approx(0.80138740)
    assert results[81,4].imag == pytest.approx(0.0)
    assert results[100,2].real == pytest.approx(0.16208914)
    assert results[100,2].imag == pytest.approx(-0.01199462)
    for i in range(0,100):
        with subtests.test("Values add to 1", i =i):
            assert results[i,1].real + results[i,4] == pytest.approx(1.0)
    for i in range(0,100):
        with subtests.test("No imaginary Populations", i=i):
            assert results[i,1].imag <= 1e-5
            assert results[i,4].imag <= 1e-5
    for i in range(0,100):
        with subtests.test("No negative Populations", i=i):
            assert np.absolute(results[i,1].real) >= -1e-5
            assert np.absolute(results[i,4].real) >= -1e-5
    for i in range(0,100):
        with subtests.test("Hermitian matrix", i=i):
            assert results[i,2].imag == pytest.approx(-1.0*results[i,3].imag)
            assert results[i,2].real == pytest.approx(results[i,3].real)
    for i in range(0,100):
        with subtests.test("No illegally large coherences", i=i): # Tolerance of 1% allowed
            assert np.sqrt(np.absolute(results[i,1]))*np.sqrt(np.absolute(results[i,4])) >= 0.99*np.abs(results[i,2])
            assert np.sqrt(np.absolute(results[i,1]))*np.sqrt(np.absolute(results[i,4])) >= 0.99*np.abs(results[i,3])


def test4(subtests,tmp_path):
    """This tests a spin-boson calculation with a Drude-Lorentz and a
    Brownian bath with the Pade decomposition. 
    """
    bath_simulation = gen_bcf(
        re_d=[540], # Reorganization energy (cm^{-1})
        width_d=[70], # Width of Drude-Lorentz spectral density (cm^{-1})
        freq_b=[1243], # Brownian spectral density frequency (cm^{-1})
        re_b=[161.6], # Brownian spectral reorganization energy (cm^{-1})
        width_b=[10], # Brownian spectral width (cm^{-1})
        temperature=300, # Temperature of the bath
        decomposition_method='Pade',
        n_ltc=1,) # Low temperature correction terms
    end_time = 10 # Propagation time in fs
    dt = 1 # Time step size in fs
    wfn = np.array([0.0, 1.0], dtype=np.complex128) # Initial wavefunction
    out=os.path.join(tmp_path,'hr1')

    # Generate the propagator that will advance the system
    propagator = system_single_bath(
       fname=out, # Specify output file
       init_rdo=np.outer(wfn, wfn.conj()), # Set system initial condition
       sys_ham=np.array([[-750.0,300.0],[300.0,750.0]], dtype=np.complex128), # Set the system Hamiltonian (cm^{-1})
       sys_op=np.array([[-0.5,0.0], [0.0,0.5]], dtype=np.complex128), # Set the H_{SB} system-bath coupling operator(s) (cm^{-1})
       bath_correlation=bath_simulation, # Specify bath correlation function(s) generated by gen_bcf
       dim=25, # Hierarchy depth
       end_time=end_time, # End time of the simulation
       step_time=dt,) # Time step size
    # Perform the dynamics simulation and generate a progress bar
    progress_bar = tqdm(propagator,total=ceil(end_time/dt))
    for _t in progress_bar:
       progress_bar.set_description(f'@{_t: .2f} fs')

    # Load results from the output file into a local array
    results = np.loadtxt(out+".dat.log",dtype=np.complex128)
    assert results[9,1].real == pytest.approx(0.13728365)
    assert results[9,1].imag == pytest.approx(0.0)
    assert results[8,2].real == pytest.approx(0.23939003)
    assert results[8,2].imag == pytest.approx(-0.14635546)
    for i in range(0,10):
        with subtests.test("Values add to 1", i =i):
            assert results[i,1].real + results[i,4] == pytest.approx(1.0)
    for i in range(0,10):
        with subtests.test("No imaginary Populations", i=i):
            assert results[i,1].imag <= 1e-5
            assert results[i,4].imag <= 1e-5
    for i in range(0,10):
        with subtests.test("No negative Populations", i=i):
            assert np.absolute(results[i,1].real) >= -1e-5
            assert np.absolute(results[i,4].real) >= -1e-5
    for i in range(0,10):
        with subtests.test("Hermitian matrix", i=i):
            assert results[i,2].imag == pytest.approx(-1.0*results[i,3].imag)
            assert results[i,2].real == pytest.approx(results[i,3].real)
    for i in range(0,10):
        with subtests.test("No illegally large coherences", i=i): # Tolerance of 1% allowed
            assert np.sqrt(np.absolute(results[i,1]))*np.sqrt(np.absolute(results[i,4])) >= 0.99*np.abs(results[i,2])
            assert np.sqrt(np.absolute(results[i,1]))*np.sqrt(np.absolute(results[i,4])) >= 0.99*np.abs(results[i,3])


def test5(subtests,tmp_path):
    """This function tests a spin-boson problem with a Drude-Lorentz bath with
    the Pade decomposition."""
    bath_simulation = gen_bcf(
        re_d=[540,300], # Reorganization energy (cm^{-1})
        width_d=[70,35], # Width of Drude-Lorentz spectral density (cm^{-1})
        temperature=150, # Temperature of the bath
        decomposition_method='Pade',
        n_ltc=3,) # Low temperature correction terms
    end_time = 10 # Propagation time in fs
    dt = 1 # Time step size in fs
    wfn = np.array([0.0, 1.0], dtype=np.complex128) # Initial wavefunction
    out=os.path.join(tmp_path,'hr1')

    # Generate the propagator that will advance the system
    propagator = system_single_bath(
       fname=out, # Specify output file
       init_rdo=np.outer(wfn, wfn.conj()), # Set system initial condition
       sys_ham=np.array([[-750.0,300.0],[300.0,750.0]], dtype=np.complex128), # Set the system Hamiltonian (cm^{-1})
       sys_op=np.array([[-0.5,0.0], [0.0,0.5]], dtype=np.complex128), # Set the H_{SB} system-bath coupling operator(s) (cm^{-1})
       bath_correlation=bath_simulation, # Specify bath correlation function(s) generated by gen_bcf
       dim=25, # Hierarchy depth
       end_time=end_time, # End time of the simulation
       step_time=dt,) # Time step size
    # Perform the dynamics simulation and generate a progress bar
    progress_bar = tqdm(propagator,total=ceil(end_time/dt))
    for _t in progress_bar:
       progress_bar.set_description(f'@{_t: .2f} fs')

    # Load results from the output file into a local array
    results = np.loadtxt(out+".dat.log",dtype=np.complex128)
    assert results[2,3].real == pytest.approx(0.03057187)
    assert results[9,4].real == pytest.approx(0.86644502)
    assert results[9,4].imag == pytest.approx(0.0)
    assert results[7,2].real == pytest.approx(0.23955658)
    assert results[7,2].imag == pytest.approx(-0.15911262)
    for i in range(0,10):
        with subtests.test("Values add to 1", i =i):
            assert results[i,1].real + results[i,4] == pytest.approx(1.0)
    for i in range(0,10):
        with subtests.test("No imaginary Populations", i=i):
            assert results[i,1].imag <= 1e-5
            assert results[i,4].imag <= 1e-5
    for i in range(0,10):
        with subtests.test("No negative Populations", i=i):
            assert np.absolute(results[i,1].real) >= -1e-5
            assert np.absolute(results[i,4].real) >= -1e-5
    for i in range(0,10):
        with subtests.test("Hermitian matrix", i=i):
            assert results[i,2].imag == pytest.approx(-1.0*results[i,3].imag)
            assert results[i,2].real == pytest.approx(results[i,3].real)
    for i in range(0,10):
        with subtests.test("No illegally large coherences", i=i): # Tolerance of 1% allowed
            assert np.sqrt(np.absolute(results[i,1]))*np.sqrt(np.absolute(results[i,4])) >= 0.99*np.abs(results[i,2])
            assert np.sqrt(np.absolute(results[i,1]))*np.sqrt(np.absolute(results[i,4])) >= 0.99*np.abs(results[i,3])


def test6(subtests,tmp_path):
    """This function tests a spin-boson problem with a Drude-Lorentz bath
    and the Matsubara decomposition.
    """
    bath_simulation = gen_bcf(
        re_d=[540], # Reorganization energy (cm^{-1})
        width_d=[70], # Width of Drude-Lorentz spectral density (cm^{-1})
        temperature=400, # Temperature of the bath
        decomposition_method='Matsubara',
        n_ltc=1,) # Low temperature correction terms
    end_time = 100 # Propagation time in fs
    dt = 1 # Time step size in fs
    wfn = np.array([0.0, 1.0], dtype=np.complex128) # Initial wavefunction
    out=os.path.join(tmp_path,'hr1')

    # Generate the propagator that will advance the system
    propagator = system_single_bath(
       fname=out, # Specify output file
       init_rdo=np.outer(wfn, wfn.conj()), # Set system initial condition
       sys_ham=np.array([[-750.0,300.0],[300.0,750.0]], dtype=np.complex128), # Set the system Hamiltonian (cm^{-1})
       sys_op=np.array([[-0.5,0.0], [0.0,0.5]], dtype=np.complex128), # Set the H_{SB} system-bath coupling operator(s) (cm^{-1})
       bath_correlation=bath_simulation, # Specify bath correlation function(s) generated by gen_bcf
       dim=15, # Hierarchy depth
       end_time=end_time, # End time of the simulation
       frame_method='train',
       step_time=dt,) # Time step size
    # Perform the dynamics simulation and generate a progress bar
    progress_bar = tqdm(propagator,total=ceil(end_time/dt))
    for _t in progress_bar:
       progress_bar.set_description(f'@{_t: .2f} fs')

    # Load results from the output file into a local array
    results = np.loadtxt(out+".dat.log",dtype=np.complex128)
    assert results[25,3].real == pytest.approx(0.16789454)
    assert results[25,3].imag == pytest.approx(0.01214597)
    assert results[54,1].real == pytest.approx(0.16212476)
    assert results[54,1].imag == pytest.approx(0.0)
    assert results[81,4].real == pytest.approx(0.80138740)
    assert results[81,4].imag == pytest.approx(0.0)
    assert results[100,2].real == pytest.approx(0.16208914)
    assert results[100,2].imag == pytest.approx(-0.01199462)
    for i in range(0,100):
        with subtests.test("Values add to 1", i =i):
            assert results[i,1].real + results[i,4] == pytest.approx(1.0)
    for i in range(0,100):
        with subtests.test("No imaginary Populations", i=i):
            assert results[i,1].imag <= 1e-5
            assert results[i,4].imag <= 1e-5
    for i in range(0,100):
        with subtests.test("No negative Populations", i=i):
            assert np.absolute(results[i,1].real) >= -1e-5
            assert np.absolute(results[i,4].real) >= -1e-5
    for i in range(0,100):
        with subtests.test("Hermitian matrix", i=i):
            assert results[i,2].imag == pytest.approx(-1.0*results[i,3].imag)
            assert results[i,2].real == pytest.approx(results[i,3].real)
    for i in range(0,100):
        with subtests.test("No illegally large coherences", i=i): # Tolerance of 1% allowed
            assert np.sqrt(np.absolute(results[i,1]))*np.sqrt(np.absolute(results[i,4])) >= 0.99*np.abs(results[i,2])
            assert np.sqrt(np.absolute(results[i,1]))*np.sqrt(np.absolute(results[i,4])) >= 0.99*np.abs(results[i,3])

