# Import statements for simulation
from math import ceil
import os
import json as json
import numpy as np
from tqdm import tqdm
from tenso.prototypes.bath import gen_bcf
from math import ceil
from tenso.prototypes.heom import system_multibath

# Generate the decomposed bath correlation function
# for HEOM propagation
bath_simulation = gen_bcf(
    re_b=[200], # Drude-Lorentz Reorganization energy (cm^{-1})
    width_b=[10], # Drude-Lorentz spectral density cut-off frequency (cm^{-1})
    freq_b=[50],
    temperature=300, # Temperature of this bath
    decomposition_method='Pade',
    n_ltc=2,) # Low temperature correction terms
end_time = 200 # Propagation time in fs
dt = 1 # Time step size in fs
wfn = np.array([0.0, 1.0], dtype=np.complex128) # Initial wavefunction
out="heom" # Base name for the output

# Generate the propagator to evolve the system density matrix
propagator = system_multibath( 
    fname=out, # Specify output file
    init_rdo=np.outer(wfn, wfn.conj()), # Set system initial condition
    sys_ham=np.array([[-750.0,300.0],[300.0,750.0]], dtype=np.complex128), # Set the system Hamiltonian (cm^{-1})
    sys_ops=[np.array([[-0.5,0.0], [0.0,0.5]], dtype=np.complex128)], # Set the H_{SB} system-bath coupling operator(s) (cm^{-1})
    bath_correlations=[bath_simulation], # Specify bath correlation function(s) generated by gen_bcf
    dim=20, # Hierarchy depth
    end_time=end_time, # End time of the simulation
    step_time=dt,) # Time step size
# Perform the dynamics simulation and generate a progress bar 
progress_bar = tqdm(propagator,total=ceil(end_time/dt))
for _t in progress_bar:
    progress_bar.set_description(f'@{_t: .2f} fs')
